In [1]:
import numpy as np
import scipy as sp
import pandas as pd
import os

from sklearn.preprocessing import minmax_scale
from sklearn.impute import KNNImputer
from scipy import stats
from collections import Counter

import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)



In [2]:
df = pd.read_csv('Myocardial.csv').fillna(np.nan)


columns_to_select = list(df.columns.values) ## here extract the columns present in the dtaset automatically
X = df[columns_to_select].values.tolist()

print(len(X[0]))
df_for_analisis = pd.DataFrame.from_records(X)



list_of_index = np.arange(len(X[0])).tolist() # Empieza en 0   # Array must be a list

Y = [ele.pop(-1) for ele in X]   ## Delete Y
print(len(X[0]))
X = [sublist[:111] for sublist in X]   # Delete features greater than 112
print(len(X[0]))

# basic statistics
nans = [np.sum((df_for_analisis.isna()[i]))/len(df_for_analisis) for i in range(len(df_for_analisis.mean().tolist()))]
print("Percentage of Nan by columns:")
print(np.around(nans,2).tolist())

deleted_indexes = [i for i in range(len(nans)) if nans[i] > 0.25]
print("deleted indexes: ", deleted_indexes)


X = np.delete(X, deleted_indexes, axis=1) # delete rows with more than 0.5 of Nan
X = np.delete(X, [0], axis=1)               # delete id patients column


for i in range(len(X)):
    for j in range(len(X[0])):

        if np.isnan(X[i][j]) == True:
            X[i][j] = -9.0


[list_of_index.remove(ele) for ele in deleted_indexes]
list_of_index.remove(0)

print("list of index: ")
print(list_of_index)

X = np.array(X, dtype='float').tolist()

imputer = KNNImputer(missing_values = -9.0, n_neighbors=5)
X = imputer.fit_transform(X)


# basic statistics
print("Mean by columns (original dataset):")
print(np.around(df_for_analisis.mean(),2).tolist()) #string features are avoided
print("Variance by columns (original dataset):")
print(np.around(df_for_analisis.var(),5).tolist())
varianza = df_for_analisis.var().tolist()

min_max_index = []
binary_index = []
z_score_index = []
i = 0


"""
for indx in list_of_index:

    z = Counter(X[:,i])
    
    if len(list(z.keys())) == 2:
        binary_index.append(indx)
        i = i+1
    else:
        if len(list(z.keys())) > 10:
            X[:,i] = stats.zscore(X[:,i])
            z_score_index.append(indx)
            i = i + 1

        else:
            X[:,i] = minmax_scale(X[:,i])
            min_max_index.append(indx)
            i = i + 1
"""

print("Binary index: ")
print(binary_index)
print("Min Max index: ")
print(min_max_index)
print("Z score index: ")
print(z_score_index)

#X = stats.zscore(X, axis=0)
X = minmax_scale(X)
dataset_name = "Myocardial"

#np.save(r'attributes_' + dataset_name + '.npy', np.array(X))
#np.save(r'target_' + dataset_name + '.npy', np.array(Y))

#np.save(r'index' + dataset_name + '.npy', np.array(list_of_index))
#np.save(r'inf_index.npy', np.array(informative_attributes))




124
123
111
Percentage of Nan by columns:
[0.0, 0.0, 0.0, 0.0, 0.06, 0.04, 0.03, 0.96, 0.01, 0.0, 0.15, 0.03, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.0, 0.0, 0.0, 0.0, 0.0, 0.63, 0.63, 0.16, 0.16, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.05, 0.05, 0.05, 0.04, 0.0, 0.09, 0.09, 0.09, 0.09, 0.09, 0.09, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.22, 0.22, 0.22, 0.22, 0.17, 0.17, 1.0, 0.07, 0.12, 0.07, 0.01, 0.06, 0.08, 0.39, 0.4, 0.4, 0.01, 0.0, 0.06, 0.08, 0.01, 0.06, 0.08, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
deleted indexes:  [7, 34, 35, 88, 95, 96, 97]
list of index: 
[1, 2, 3, 4, 5, 6, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 5

In [3]:
len(X[0])

103

In [10]:
X = [[0,1,2], [1,5,10]]
#X = minmax_scale(X, axis = 0)
X = stats.zscore(X)
print(X)

[[-1. -1. -1.]
 [ 1.  1.  1.]]


In [12]:
stats.zscore([1,5])

array([-1.,  1.])